apiVersion: v2
name: cleanuparr
description: A Helm chart for Cleanuparr - automation tool for cleanup of unwanted or blocked files in Sonarr, Radarr
type: application
version: 1.0.0
appVersion: "latest"
