image:
  repository: ghcr.io/cleanuparr/cleanuparr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 11011

persistence:
  config:
    enabled: true
    storageClass: freenas-iscsi-csi
    accessMode: ReadWriteOnce
    size: 1Gi
    # volumeName: "" # Optional: Specify an existing PV to bind to
  torrents:
    enabled: false
    existingClaim: ""
    mountPath: /torrents

env:
  PORT: "11011"
  TZ: "America/New_York"
  PUID: "1000"
  PGID: "1000"

resources:
  requests:
    memory: 256Mi
    cpu: 140m
  limits:
    memory: 1Gi


metrics:
  enabled: false

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts: []
  tls: []
