apiVersion: v2
name: qbittorrent-exporter
description: A Helm chart for qBittorrent Prometheus Exporter - exports metrics from qBittorrent to Prometheus
type: application
version: 1.0.0
appVersion: "v1.5.2"
